# Generated by Django 4.2.4 on 2023-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('date', models.DateField()),
                ('game_data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
